In [2]:
import pandas as pd
import numpy as np

In [3]:
superstore_df = pd.read_excel("Superstore_USA.xlsx")

In [4]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [6]:
superstore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [8]:
superstore_df1 = pd.read_excel("Superstore_USA.xlsx", sheet_name="Returns") #Find out how return that we ahve recived and with a product id

In [9]:
superstore_df1

      Order ID    Status
0           65  Returned
1          612  Returned
2          614  Returned
3          678  Returned
4          710  Returned
...        ...       ...
1629    182681  Returned
1630    182683  Returned
1631    182750  Returned
1632    182781  Returned
1633    182906  Returned

[1634 rows x 2 columns]

In [10]:
superstore_merged_df = pd.merge(superstore_df,superstore_df1, on="Order ID",) #try  to join order and return data both in sql and pandas

In [11]:
superstore_merged_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,Status
0,1359,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,New York,New York City,10012,2011-04-20,2011-04-24,-6.8200,9,54.79,9895,Returned
1,1950,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,2010-04-04,2010-04-06,112.0600,47,228.46,13959,Returned
2,1951,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,...,Washington,Seattle,98103,2010-04-04,2010-04-06,16.7900,19,77.61,13959,Returned
3,5055,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,Washington,Seattle,98103,2013-08-16,2013-08-18,-89.0600,52,190.52,36038,Returned
4,5573,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,...,North Carolina,Charlotte,28204,2013-08-12,2013-08-12,-81.9413,76,912.06,39490,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,986,Not Specified,0.06,37.94,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,2013-01-04,2013-01-06,-33.9680,3,113.14,7107,Returned
94,987,Not Specified,0.10,55.29,5.08,3075,Gordon Brandt,Regular Air,Corporate,Office Supplies,...,California,Los Angeles,90061,2013-01-04,2013-01-05,163.1200,35,1886.52,7107,Returned
95,6041,Medium,0.05,4.28,6.18,3075,Gordon Brandt,Express Air,Corporate,Office Supplies,...,California,Los Angeles,90061,2013-06-25,2013-06-27,-22.5600,12,73.71,42823,Returned
96,1910,High,0.05,14.48,1.99,3079,Andrew Levine,Regular Air,Consumer,Technology,...,Pennsylvania,Philadelphia,19112,2012-09-30,2012-10-02,165.2000,96,1337.67,13638,Returned
97,6625,High,0.06,128.24,12.65,3251,Peter Brooks,Regular Air,Small Business,Furniture,...,New York,New York City,10112,2012-09-11,2012-09-13,1844.9600,92,12002.16,47109,Returned

In [12]:
superstore_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98 entries, 0 to 97
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                98 non-null     int64
 1   Order Priority        98 non-null     object
 2   Discount              98 non-null     float64
 3   Unit Price            98 non-null     float64
 4   Shipping Cost         98 non-null     float64
 5   Customer ID           98 non-null     int64
 6   Customer Name         98 non-null     object
 7   Ship Mode             98 non-null     object
 8   Customer Segment      98 non-null     object
 9   Product Category      98 non-null     object
 10  Product Sub-Category  98 non-null     object
 11  Product Container     98 non-null     object
 12  Product Name          98 non-null     object
 13  Product Base Margin   96 non-null     float64
 14  Region                98 non-null     object
 15  State or Province     98 non-null     object
 16  City                  98 non-null     object
 17  Postal Code           98 non-null     int64
 18  Order Date            98 non-null     datetime64[ns]
 19  Ship Date             98 non-null     datetime64[ns]
 20  Profit                98 non-null     float64
 21  Quantity ordered new  98 non-null     int64
 22  Sales                 98 non-null     float64
 23  Order ID              98 non-null     int64
 24  Status                98 non-null     object
dtypes: datetime64[ns](2), float64(6), int64(5), object(12)
memory usage: 19.9+ KB

In [13]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [14]:
superstore_df["Customer ID"].nunique() #Try to find out how many unique customer that we have

2703

In [15]:
superstore_df["Region"].unique()

array(['Central', 'West', 'East', 'South'], dtype=object)

In [17]:
superstore_df2 = pd.read_excel("Superstore_USA.xlsx",sheet_name="Users") #try to find out in how many regions we are selling a product and who is a manager for a respective region

In [18]:
superstore_df2

    Region  Manager
0  Central    Chris
1     East     Erin
2    South      Sam
3     West  William

In [19]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [22]:
superstore_df["Ship Mode"].value_counts()

Regular Air       7036
Delivery Truck    1283
Express Air       1107
Name: Ship Mode, dtype: int64

In [23]:
shipment_df = pd.DataFrame(superstore_df["Ship Mode"].value_counts()) #find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

In [24]:
shipment_df

                Ship Mode
Regular Air          7036
Delivery Truck       1283
Express Air          1107

In [27]:
shipment_df["shipment_percentage"] = (shipment_df["Ship Mode"]/shipment_df["Ship Mode"].sum())*100 #find out how many different differnet shipement mode that we have and what is a percentage usablity of all the shipment mode with respect to dataset

In [28]:
shipment_df

                Ship Mode  shipment_percentage
Regular Air          7036            74.644600
Delivery Truck       1283            13.611288
Express Air          1107            11.744112

In [29]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Region,State or Province,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Central,Illinois,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,West,Washington,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,East,West Virginia,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,East,West Virginia,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,West,Wyoming,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,West,Wyoming,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533

In [30]:
superstore_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9426 entries, 0 to 9425
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Row ID                9426 non-null   int64
 1   Order Priority        9426 non-null   object
 2   Discount              9426 non-null   float64
 3   Unit Price            9426 non-null   float64
 4   Shipping Cost         9426 non-null   float64
 5   Customer ID           9426 non-null   int64
 6   Customer Name         9426 non-null   object
 7   Ship Mode             9426 non-null   object
 8   Customer Segment      9426 non-null   object
 9   Product Category      9426 non-null   object
 10  Product Sub-Category  9426 non-null   object
 11  Product Container     9426 non-null   object
 12  Product Name          9426 non-null   object
 13  Product Base Margin   9354 non-null   float64
 14  Region                9426 non-null   object
 15  State or Province     9426 non-null   object
 16  City                  9426 non-null   object
 17  Postal Code           9426 non-null   int64
 18  Order Date            9426 non-null   datetime64[ns]
 19  Ship Date             9426 non-null   datetime64[ns]
 20  Profit                9426 non-null   float64
 21  Quantity ordered new  9426 non-null   int64
 22  Sales                 9426 non-null   float64
 23  Order ID              9426 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(5), object(11)
memory usage: 1.7+ MB

In [31]:
superstore_df["order_day"] = superstore_df["Order Date"].dt.day

In [32]:
superstore_df["ship_day"] = superstore_df["Ship Date"].dt.day

In [33]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,City,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,order_day,ship_day
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,Addison,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,28,30
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Anacortes,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522,7,8
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,Anacortes,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,27,28
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,Anacortes,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,27,28
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,Anacortes,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,27,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,Charleston,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,14,15
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,Charleston,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,14,14
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,Charleston,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533,12,14
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,Cheyenne,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530,8,11
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,Cheyenne,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533,12,14

In [36]:
superstore_df["day_difference"] = superstore_df["ship_day"] - superstore_df["order_day"]

In [37]:
superstore_df # Create a new coulmn and try to find our a diffrence between order date and shipment date

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,order_day,ship_day,day_difference
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,28,30,2
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522,7,8,1
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,27,28,1
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,27,28,1
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,27,27,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,14,15,1
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,14,14,0
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533,12,14,2
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530,8,11,3
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533,12,14,2

In [38]:
superstore_df[superstore_df["day_difference"]>10] #base on question number 8 find out for which order id we have shipment duration more than 10 days

Empty DataFrame
Columns: [Row ID, Order Priority, Discount, Unit Price, Shipping Cost, Customer ID, Customer Name, Ship Mode, Customer Segment, Product Category, Product Sub-Category, Product Container, Product Name, Product Base Margin, Region, State or Province, City, Postal Code, Order Date, Ship Date, Profit, Quantity ordered new, Sales, Order ID, order_day, ship_day, day_difference]
Index: []

[0 rows x 27 columns]

In [39]:
superstore_merged_df = pd.merge(superstore_df,superstore_df1, on="Order ID")

In [44]:
superstore_merged_df.head(60)

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,order_day,ship_day,day_difference,Status
0,1359,Low,0.05,5.85,2.27,21,Tony Wilkins Winters,Regular Air,Small Business,Office Supplies,...,2011-04-20,2011-04-24,-6.820000,9,54.79,9895,20,24,4,Returned
1,1950,Medium,0.01,4.91,0.50,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,2010-04-04,2010-04-06,112.060000,47,228.46,13959,4,6,2,Returned
2,1951,Medium,0.09,4.00,1.30,117,Linda Weiss,Express Air,Home Office,Office Supplies,...,2010-04-04,2010-04-06,16.790000,19,77.61,13959,4,6,2,Returned
3,5055,High,0.02,3.28,5.00,117,Linda Weiss,Regular Air,Home Office,Office Supplies,...,2013-08-16,2013-08-18,-89.060000,52,190.52,36038,16,18,2,Returned
4,5573,Low,0.02,11.97,5.81,272,Eleanor Swain,Regular Air,Small Business,Office Supplies,...,2013-08-12,2013-08-12,-81.941300,76,912.06,39490,12,12,0,Returned
5,5574,Low,0.03,159.31,60.00,272,Eleanor Swain,Delivery Truck,Small Business,Furniture,...,2013-08-12,2013-08-16,11.034900,34,5689.28,39490,12,16,4,Returned
6,5302,High,0.01,8.33,1.99,308,Glen Caldwell,Regular Air,Small Business,Technology,...,2010-08-14,2010-08-15,10.740000,32,280.62,37760,14,15,1,Returned
7,5303,High,0.04,85.99,0.99,308,Glen Caldwell,Regular Air,Small Business,Technology,...,2013-08-14,2013-08-16,897.867000,76,5546.06,37760,14,16,2,Returned
8,5257,Low,0.09,550.98,64.59,349,Kim Weiss,Delivery Truck,Home Office,Furniture,...,2012-09-09,2012-09-11,-1770.965977,76,40136.93,37414,9,11,2,Returned
9,6643,Critical,0.02,5.98,5.46,349,Kim Weiss,Regular Air,Home Office,Office Supplies,...,2012-12-10,2012-12-11,-80.903900,62,374.26,47265,10,11,1,Returned
10,979,Medium,0.01,280.98,57.00,478,Michael Wiggins,Delivery Truck,Small Business,Furniture,...,2011-02-08,2011-02-09,-416.700000,44,12296.49,7079,8,9,1,Returned
11,980,Medium,0.03,6.48,5.94,478,Michael Wiggins,Regular Air,Small Business,Office Supplies,...,2011-02-08,2011-02-10,-34.910000,18,128.13,7079,8,10,2,Returned
12,1147,Medium,0.08,2.94,0.96,491,Toni Swanson,Regular Air,Consumer,Office Supplies,...,2010-05-15,2010-05-17,-2.120000,23,66.70,8353,15,17,2,Returned
13,1146,Medium,0.06,8.32,2.38,491,Toni Swanson,Regular Air,Consumer,Technology,...,2013-05-15,2013-05-17,-36.630000,44,371.28,8353,15,17,2,Returned
14,2368,Medium,0.00,6.88,2.00,553,Kristine Connolly,Express Air,Home Office,Office Supplies,...,2010-01-28,2010-01-29,34.068000,36,267.53,17155,28,29,1,Returned
15,2369,Medium,0.03,32.48,35.00,553,Kristine Connolly,Express Air,Home Office,Office Supplies,...,2013-01-28,2013-01-28,-1440.432000,34,1168.35,17155,28,28,0,Returned
16,6813,Low,0.00,12.97,1.49,604,Lindsay P Ashley,Regular Air,Home Office,Office Supplies,...,2011-01-11,2011-01-13,58.466400,27,360.70,48487,11,13,2,Returned
17,7828,Low,0.05,1.82,1.00,604,Lindsay P Ashley,Regular Air,Home Office,Office Supplies,...,2013-09-30,2013-10-02,0.860000,84,154.60,55968,30,2,-28,Returned
18,7893,Not Specified,0.00,236.97,59.24,640,Neal Wolfe,Delivery Truck,Consumer,Furniture,...,2010-02-14,2010-02-15,1192.040000,34,6686.34,56452,14,15,1,Returned
19,3749,Critical,0.02,120.98,30.00,699,Jenny Gold,Delivery Truck,Consumer,Furniture,...,2011-07-23,2011-07-24,-64.140000,14,1711.44,26784,23,24,1,Returned
20,3750,Critical,0.09,13.99,7.51,699,Jenny Gold,Regular Air,Consumer,Technology,...,2013-07-23,2013-07-24,-37.940700,46,613.65,26784,23,24,1,Returned
21,8079,Low,0.09,217.85,29.10,699,Jenny Gold,Delivery Truck,Consumer,Furniture,...,2013-04-22,2013-04-27,-526.478095,35,5740.62,57638,22,27,5,Returned
22,8080,Low,0.07,11.48,5.43,699,Jenny Gold,Regular Air,Consumer,Office Supplies,...,2013-04-22,2013-04-24,78.890000,49,570.43,57638,22,24,2,Returned
23,8081,Low,0.08,2.08,2.56,699,Jenny Gold,Regular Air,Consumer,Office Supplies,...,2013-04-22,2013-04-24,-85.580000,49,100.08,57638,22,24,2,Returned
24,7038,Medium,0.05,6.48,7.37,894,Gail Rankin Cole,Express Air,Corporate,Office Supplies,...,2011-08-18,2011-08-19,-47.670000,25,182.21,50246,18,19,1,Returned
25,7234,Low,0.09,25.98,4.08,949,Ernest Oh,Regular Air,Consumer,Office Supplies,...,2013-03-04,2013-03-13,129.810000,34,823.98,51559,4,13,9,Returned
26,6711,High,0.00,6.68,5.66,1044,Erin Ballard,Regular Air,Home Office,Office Supplies,...,2010-08-27,2010-08-29,-76.940000,90,617.40,47813,27,29,2,Returned
27,4398,Low,0.09,5.98,1.49,1044,Erin Ballard,Express Air,Home Office,Office Supplies,...,2012-03-20,2012-03-22,87.601000,56,342.87,31303,20,22,2,Returned
28,7966,High,0.05,7.99,5.03,1060,Gene Gilliam,Regular Air,Small Business,Technology,...,2011-02-03,2011-02-05,-147.090020,34,232.42,56931,3,5,2,Returned
29,2474,Medium,0.01,110.98,30.00,1104,Timothy Ross,Delivery Truck,Home Office,Furniture,...,2012-04-12,2012-04-13,-183.260000,4,473.88,17985,12,13,1,Returned
30,2475,Medium,0.07,20.99,3.30,1104,Timothy Ross,Regular Air,Home Office,Technology,...,2012-04-12,2012-04-14,-133.309000,56,950.91,17985,12,14,2,Returned
31,3435,Critical,0.03,5.34,5.63,1106,Maxine Collier Grady,Regular Air,Consumer,Office Supplies,...,2012-06-11,2012-06-12,-60.720000,36,208.73,24519,11,12,1,Returned
32,7659,Critical,0.06,5.98,5.46,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,2012-08-28,2012-08-29,-57.640000,63,389.67,54914,28,29,1,Returned
33,7660,Critical,0.06,12.44,6.27,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,2012-08-28,2012-08-30,-27.830000,14,181.16,54914,28,30,2,Returned
34,4697,High,0.08,10.35,0.99,1106,Maxine Collier Grady,Regular Air,Small Business,Office Supplies,...,2013-10-19,2013-10-21,113.630000,59,567.41,33477,19,21,2,Returned
35,7632,Medium,0.09,130.98,30.00,1217,Billy Perry Browning,Delivery Truck,Small Business,Furniture,...,2010-04-28,2010-05-01,-421.760000,41,5258.94,54595,28,1,-27,Returned
36,7631,Medium,0.02,8.34,2.64,1217,Billy Perry Browning,Regular Air,Small Business,Office Supplies,...,2013-04-28,2013-04-30,6.790000,30,250.29,54595,28,30,2,Returned
37,2099,Not Specified,0.09,28.15,8.99,1217,Billy Perry Browning,Express Air,Small Business,Office Supplies,...,2012-12-21,2012-12-23,-7.800000,92,2400.26,15009,21,23,2,Returned
38,2100,Not Specified,0.08,7.78,2.50,1217,Billy Perry Browning,Express Air,Small Business,Office Supplies,...,2012-12-21,2012-12-22,61.090000,56,458.86,15009,21,22,1,Returned
39,7810,Medium,0.00,7.10,6.05,1228,Hazel Jennings,Regular Air,Small Business,Office Supplies,...,2010-02-16,2010-02-17,-60.145000,28,208.83,55874,16,17,1,Returned
40,7811,Medium,0.01,4.98,4.62,1228,Hazel Jennings,Express Air,Small Business,Technology,...,2010-02-16,2010-02-18,-111.720000,41,228.30,55874,16,18,2,Returned
41,7812,Medium,0.06,5.68,1.39,1228,Hazel Jennings,Regular Air,Small Business,Office Supplies,...,2010-02-16,2010-02-16,33.010000,24,129.53,55874,16,16,0,Returned
42,5882,Low,0.04,315.98,19.99,1228,Hazel Jennings,Regular Air,Small Business,Office Supplies,...,2013-01-27,2013-02-01,1059.232600,23,7325.68,41760,27,1,-26,Returned
43,5883,Low,0.00,9.98,12.52,1228,Hazel Jennings,Regular Air,Small Business,Furniture,...,2013-01-27,2013-02-03,-213.088000,24,269.95,41760,27,3,-24,Returned
44,5884,Low,0.08,115.99,2.50,1228,Hazel Jennings,Regular Air,Small Business,Technology,...,2013-01-27,2013-02-01,-446.195200,8,783.68,41760,27,1,-26,Returned
45,5885,Low,0.05,95.99,8.99,1228,Hazel Jennings,Regular Air,Small Business,Technology,...,2013-01-27,2013-02-01,278.780400,44,3555.35,41760,27,1,-26,Returned
46,7466,Critical,0.04,165.98,19.99,1246,Lois Hansen,Regular Air,Home Office,Office Supplies,...,2013-05-24,2013-05-26,163.803500,8,1390.61,53285,24,26,2,Returned
47,3155,Not Specified,0.05,30.98,6.50,1280,Harold Albright,Express Air,Corporate,Technology,...,2011-12-22,2011-12-24,-77.890000,19,587.67,22656,22,24,2,Returned
48,6959,High,0.09,2.94,0.81,1313,Katherine Knight,Regular Air,Corporate,Office Supplies,...,2012-06-15,2012-06-17,23.740000,58,164.27,49762,15,17,2,Returned
49,2143,Critical,0.02,4.54,5.83,1314,Keith Marsh,Regular Air,Home Office,Office Supplies,...,2011-09-13,2011-09-14,-74.405000,38,183.00,15303,13,14,1,Returned
50,2144,Critical,0.02,28.48,8.99,1314,Keith Marsh,Regular Air,Home Office,Technology,...,2011-09-13,2011-09-15,-108.140000,33,965.16,15303,13,15,2,Returned
51,5252,Critical,0.08,26.64,5.30,1314,Keith Marsh,Regular Air,Home Office,Furniture,...,2012-04-01,2012-04-02,90.040000,32,813.66,37380,1,2,1,Returned
52,5253,Critical,0.00,9.99,4.78,1314,Keith Marsh,Regular Air,Home Office,Office Supplies,...,2012-04-01,2012-04-02,74.730000,53,571.93,37380,1,2,1,Returned
53,5254,Critical,0.07,3.55,1.43,1314,Keith Marsh,Regular Air,Home Office,Office Supplies,...,2012-04-01,2012-04-02,27.370000,47,169.19,37380,1,2,1,Returned
54,6878,High,0.08,17.67,8.99,1314,Keith Marsh,Regular Air,Home Office,Furniture,...,2012-04-11,2012-04-12,35.080000,46,795.27,49027,11,12,1,Returned
55,7626,Critical,0.01,20.24,8.99,1318,Vickie Becker,Regular Air,Home Office,Furniture,...,2011-10-04,2011-10-06,35.096000,43,938.05,54563,4,6,2,Returned
56,5231,High,0.03,35.94,6.66,1413,Pamela Wiley,Regular Air,Corporate,Office Supplies,...,2011-01-14,2011-01-15,51.244000,13,473.46,37250,14,15,1,Returned
57,7106,High,0.04,304.99,19.99,1630,Jimmy Han,Regular Air,Home Office,Office Supplies,...,2013-02-27,2013-03-01,3793.703000,33,9758.70,50721,27,1,-26,Returned
58,2771,Not Specified,0.03,150.98,66.27,1723,Constance Flowers,Delivery Truck,Corporate,Furniture,...,2011-12-05,2011-12-08,-533.440000,52,8119.28,20036,5,8,3,Returned
59,2772,Not Specified,0.03,95.99,4.90,1723,Constance Flowers,Regular Air,Corporate,Technology,...,2011-12-05,2011-12-07,307.251000,39,3240.93,20036,5,7,2,Returned

In [ ]:
no data as such found because shipment duration are not more than 9 days #Try to find out a list of a returned order which sihpment duration was more then 15 days and find out that region manager as well

In [45]:
superstore_df

,Row ID,Order Priority,Discount,Unit Price,Shipping Cost,Customer ID,Customer Name,Ship Mode,Customer Segment,Product Category,...,Postal Code,Order Date,Ship Date,Profit,Quantity ordered new,Sales,Order ID,order_day,ship_day,day_difference
0,18606,Not Specified,0.01,2.88,0.50,2,Janice Fletcher,Regular Air,Corporate,Office Supplies,...,60101,2012-05-28,2012-05-30,1.320000,2,5.90,88525,28,30,2
1,20847,High,0.01,2.84,0.93,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,98221,2010-07-07,2010-07-08,4.560000,4,13.01,88522,7,8,1
2,23086,Not Specified,0.03,6.68,6.15,3,Bonnie Potter,Express Air,Corporate,Office Supplies,...,98221,2011-07-27,2011-07-28,-47.640000,7,49.92,88523,27,28,1
3,23087,Not Specified,0.01,5.68,3.60,3,Bonnie Potter,Regular Air,Corporate,Office Supplies,...,98221,2011-07-27,2011-07-28,-30.510000,7,41.64,88523,27,28,1
4,23088,Not Specified,0.00,205.99,2.50,3,Bonnie Potter,Express Air,Corporate,Technology,...,98221,2011-07-27,2011-07-27,998.202300,8,1446.67,88523,27,27,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9421,20275,Critical,0.06,35.89,14.72,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,25314,2013-05-14,2013-05-15,137.860000,13,447.87,87532,14,15,1
9422,20276,Critical,0.00,3.34,7.49,3402,Frederick Cole,Regular Air,Consumer,Office Supplies,...,25314,2013-05-14,2013-05-14,-39.070000,3,13.23,87532,14,14,0
9423,24491,Not Specified,0.08,550.98,45.70,3402,Frederick Cole,Delivery Truck,Consumer,Furniture,...,25314,2013-09-12,2013-09-14,-1225.029097,4,2215.93,87533,12,14,2
9424,25914,High,0.10,105.98,13.99,3403,Tammy Buckley,Express Air,Consumer,Furniture,...,82001,2010-02-08,2010-02-11,349.485000,5,506.50,87530,8,11,3
9425,24492,Not Specified,0.09,7.78,2.50,3403,Tammy Buckley,Express Air,Consumer,Office Supplies,...,82001,2013-09-12,2013-09-14,78.062400,23,172.48,87533,12,14,2

In [46]:
superstore_df_region = superstore_df.groupby("Region")["Profit"].sum()

In [48]:
superstore_df_region.sort_values(ascending=False) # Gorup by region and find out which region is more profitable

Region
Central    519825.567067
East       377566.186045
West       310849.453897
South      104201.192420
Name: Profit, dtype: float64

In [50]:
superstore_df_country = superstore_df.groupby("State or Province")["Discount"].sum()

In [51]:
superstore_df_country.sort_values(ascending=False) #Try to find out overalll in which country we are giving more didscount

State or Province
California              52.28
Texas                   31.36
Illinois                29.71
New York                28.86
Florida                 26.38
Ohio                    19.71
Washington              15.48
Michigan                15.29
Pennsylvania            13.32
Minnesota               12.52
Indiana                 12.22
North Carolina          12.02
Massachusetts           11.22
Virginia                 9.80
Georgia                  9.79
Maryland                 8.85
New Jersey               8.73
Tennessee                8.55
Oregon                   8.42
Missouri                 8.09
Wisconsin                8.06
Colorado                 8.05
Utah                     7.67
Iowa                     7.15
Kansas                   6.89
Arizona                  6.86
Maine                    6.66
Alabama                  5.87
Arkansas                 5.80
Idaho                    5.57
South Carolina           5.34
Oklahoma                 5.17
Louisiana                4.86
Connecticut              4.28
Kentucky                 4.23
New Mexico               4.08
Mississippi              3.89
Nebraska                 3.59
Vermont                  3.19
District of Columbia     3.10
New Hampshire            2.62
Montana                  2.39
West Virginia            2.16
Nevada                   1.80
North Dakota             1.71
South Dakota             1.30
Wyoming                  1.15
Rhode Island             1.09
Delaware                 0.66
Name: Discount, dtype: float64

In [52]:
superstore_df["Postal Code"].unique() # Give me a list of unique postal code

array([60101, 98221, 91776, ..., 61832, 62521, 26554], dtype=int64)

In [53]:
superstore_df_customer_segment = superstore_df.groupby("Customer Segment")["Profit"].sum()

In [54]:
superstore_df_customer_segment.sort_values(ascending=False) #which customer segement is more profitalble find it out

Customer Segment
Corporate         505538.627783
Small Business    316474.592482
Home Office       283869.553814
Consumer          206559.625348
Name: Profit, dtype: float64

In [55]:
superstore_df_prod_cat = superstore_df.groupby("Product Category")["Profit"].sum()

In [56]:
superstore_df_prod_cat # try to find out the 10th most loss making product catagory . not in range only 3 prod cat

Product Category
Furniture          177354.298188
Office Supplies    451990.216492
Technology         683097.884748
Name: Profit, dtype: float64

In [57]:
superstore_df["Product Category"].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [58]:
superstore_df_prod_sb_cat = superstore_df.groupby("Product Sub-Category")["Profit"].sum()

In [67]:
superstore_df_prod_sb_cat.sort_values(ascending=True)[9] #try to find out the 10th most loss making product catagory = Computer Peripherals               87917.842513

87917.8425126

In [68]:
superstore_df_prod_sb_cat.sort_values(ascending=True)

Product Sub-Category
Tables                            -72495.061875
Bookcases                          -7708.748564
Rubber Bands                       -2841.722459
Scissors, Rulers and Trimmers      -1936.849120
Pens & Art Supplies                 1195.902840
Storage & Organization              8078.804727
Labels                             17775.320505
Paper                              35361.621738
Envelopes                          46133.223840
Computer Peripherals               87917.842513
Office Furnishings                 92209.225867
Appliances                        121651.391380
Copiers and Fax                   129156.684030
Chairs & Chairmats                165348.882760
Office Machines                   168072.833340
Binders and Binder Accessories    226572.523042
Telephones and Communication      297950.524866
Name: Profit, dtype: float64

In [69]:
superstore_df_prod_sb_cat.sort_values(ascending=False).nlargest(10) #Try to find out 10 top  product with highest margins

Product Sub-Category
Telephones and Communication      297950.524866
Binders and Binder Accessories    226572.523042
Office Machines                   168072.833340
Chairs & Chairmats                165348.882760
Copiers and Fax                   129156.684030
Appliances                        121651.391380
Office Furnishings                 92209.225867
Computer Peripherals               87917.842513
Envelopes                          46133.223840
Paper                              35361.621738
Name: Profit, dtype: float64

In [ ]:
sir, sql and mongodb portion is not done yet i have to revise that portion as i forgot some of the queries 
and with mongodb i have some problem as everytime while connecting with atlas it is generating system timeout error i dont know why